server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/browserstart?serverTimezone=GMT%2b8
    username: root
    password: tuise233

#mybatis:
#  mapper-locations: classpath:mapper/*.xml